// generate-catalog.test.ts — DOCS-01 oracle for the browsable docs catalog generator
// (Vitest harness for scripts/generate-catalog.js).
//
// Drives the COMMITTED compiled artifact scripts/generate-catalog.js (never the .ts) and asserts
// the DOCS-01 contract over the real kit (17 roles + 17 workflows):
//   (1) WRITES + EXITS 0 over the real kit, leaving the tree clean (regen == committed bytes);
//   (2) BYTE-REPRODUCIBLE: two successive regenerations are byte-identical (and equal committed);
//   (3) COMPLETE SET: all 17 role names + all 17 workflow names present, exactly 17 + 17 rows;
//   (4) FAIL-CLOSED: a tampered kit file with no `# Role:` H1 → exit 1, NO partial write — proven
//       hermetically (mirror-and-tamper into a temp dir) so the real tree is never touched;
//   (5) NO FABRICATION: workflows 12/13 cadence cell reads `UNKNOWN - verify`, never `cadence: both`,
//       and no `..` (double-period) appears anywhere (the incident-responder single-sentence edge).
//
// The generator's ROLES_DIR/WORKFLOWS_DIR/OUT are FIXED literal paths joined to its own repo root
// (path-traversal mitigation — never argv/env/content-derived). So the fail-closed case copies the
// generator .js plus a TAMPERED agent-factory/{roles,workflows} + a sentinel output into a temp
// mirror laid out as <tmp>/scripts/... and <tmp>/agent-factory/..., then runs the mirrored .js there.
// The real tree is read-only in (1)/(2)/(3)/(5) and untouched in (4).
//
// This file ships RED until Task 2 builds the committed generate-catalog.js — that is correct
// Wave-0 sequencing (the oracle is authored before the implementation).

import { describe, it, expect, afterAll } from "vitest";
import { spawnSync, type SpawnSyncReturns } from "node:child_process";
import {
  mkdtempSync,
  mkdirSync,
  cpSync,
  rmSync,
  readFileSync,
  writeFileSync,
  existsSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

const ROOT = join(import.meta.dirname, "..");
const GEN_JS = join(ROOT, "scripts", "generate-catalog.js");
const OUT = join(ROOT, "docs", "catalog", "README.md");

const tmpDirs: string[] = [];
afterAll(() => {
  for (const d of tmpDirs) rmSync(d, { recursive: true, force: true });
});

function out(r: SpawnSyncReturns<string>): string {
  return `${r.stdout ?? ""}${r.stderr ?? ""}`;
}

// The 17 role display names (from each file's `# Role:` H1) — load-bearing literals.
const ROLE_NAMES = [
  "AGENTS.md Scribe",
  "Architect/Design",
  "BA/PM",
  "Brownfield Mapper",
  "Compliance Officer",
  "Factory Coach",
  "Frontend/UI",
  "Greenfield Mapper",
  "Incident Responder",
  "Installer",
  "Orchestrator",
  "QE/E2E",
  "Release Manager",
  "Security/NFR",
  "Software Engineer",
  "System Analyst",
  "UAT Planner",
];

// The 17 workflow display names (from each file's `# Workflow:` H1) — load-bearing literals.
const WORKFLOW_NAMES = [
  "Bootstrap greenfield",
  "Bootstrap brownfield",
  "Idea to epics",
  "Epic to tickets",
  "Ticket to PR",
  "PR quality gate",
  "UAT pack",
  "Backlog refinement",
  "Sprint planning",
  "Daily sweep",
  "Sprint review",
  "Retro",
  "Release",
  "Incident",
  "UI design to build",
  "Security audit (OWASP ASVS)",
  "context read/write",
];

// Count data rows in a GitHub-flavored markdown table body for a given source-dir prefix.
// A data row links to `agent-factory/<dir>/<file>.md`; the header/separator rows do not, so this
// counts only real entries (not raw `.` or `|` tallies).
function countRowsLinkingInto(text: string, dir: string): number {
  const re = new RegExp(`agent-factory/${dir}/[^)\\s|]+\\.md`, "g");
  return (text.match(re) ?? []).length;
}

describe("generate-catalog.js (DOCS-01)", () => {
  // (1) writes the catalog + exits 0 over the real kit. The regenerated bytes equal the committed
  // bytes (parity → no-op), so the real tree is left clean. Restore defensively in finally.
  it("writes the catalog and exits 0, leaving the tree clean", () => {
    const before = readFileSync(OUT);
    const r = spawnSync("node", [GEN_JS], { encoding: "utf8" });
    try {
      expect(r.status).toBe(0);
      const after = readFileSync(OUT);
      expect(after.length).toBeGreaterThan(0);
      // The committed catalog IS the generator's deterministic output, so a regen is a no-op.
      expect(after.equals(before)).toBe(true);
    } finally {
      writeFileSync(OUT, before);
    }
  });

  // (2) byte-reproducibility: two successive regenerations produce byte-identical output, equal to
  // the committed bytes.
  it("byte-reproducible: regenerating twice yields identical bytes", () => {
    const before = readFileSync(OUT);
    try {
      const r1 = spawnSync("node", [GEN_JS], { encoding: "utf8" });
      expect(r1.status).toBe(0);
      const first = readFileSync(OUT);
      const r2 = spawnSync("node", [GEN_JS], { encoding: "utf8" });
      expect(r2.status).toBe(0);
      const second = readFileSync(OUT);
      expect(second.equals(first)).toBe(true);
      expect(second.equals(before)).toBe(true);
    } finally {
      writeFileSync(OUT, before);
    }
  });

  // (3) complete set: all 17 role names + all 17 workflow names present (incl. frontend-ui via its
  // source link, and workflows 14 + 15 + 16); exactly 17 role data rows + 17 workflow data rows.
  it("contains all 17 roles and all 17 workflows with exact row counts", () => {
    const before = readFileSync(OUT);
    try {
      const r = spawnSync("node", [GEN_JS], { encoding: "utf8" });
      expect(r.status).toBe(0);
      const text = readFileSync(OUT, "utf8");

      for (const name of ROLE_NAMES) expect(text).toContain(name);
      for (const name of WORKFLOW_NAMES) expect(text).toContain(name);

      // The frontend-ui role + workflows 14/15 source files must be linked (the finished set).
      expect(text).toContain("agent-factory/roles/frontend-ui.md");
      expect(text).toContain("agent-factory/workflows/14-ui-design-to-build.md");
      expect(text).toContain("agent-factory/workflows/15-security-audit.md");

      // Exactly 17 role rows + 17 workflow rows (count via source-link matches, not `.` tallies).
      expect(countRowsLinkingInto(text, "roles")).toBe(17);
      expect(countRowsLinkingInto(text, "workflows")).toBe(17);
    } finally {
      writeFileSync(OUT, before);
    }
  });

  // (4) fail-closed: a kit file with no `# Role:` H1 → exit 1, NO partial write. Built hermetically:
  // mirror the generator .js + a TAMPERED agent-factory/{roles,workflows} into <tmp>, plant a
  // sentinel at <tmp>/docs/catalog/README.md, run the mirrored .js, assert exit 1 AND the sentinel
  // survives unchanged (refused to write a partial). The real tree is never touched.
  it("fail-closed: a kit file with no H1 → exit 1, no partial write", () => {
    const m = mkdtempSync(join(tmpdir(), "grugops-catalog-"));
    tmpDirs.push(m);
    mkdirSync(join(m, "scripts"), { recursive: true });
    mkdirSync(join(m, "docs", "catalog"), { recursive: true });
    cpSync(GEN_JS, join(m, "scripts", "generate-catalog.js"));
    cpSync(join(ROOT, "agent-factory", "roles"), join(m, "agent-factory", "roles"), {
      recursive: true,
    });
    cpSync(
      join(ROOT, "agent-factory", "workflows"),
      join(m, "agent-factory", "workflows"),
      { recursive: true },
    );

    // Tamper: strip the `# Role:` H1 line from one mirrored role file (a missing name = drift).
    const victim = join(m, "agent-factory", "roles", "orchestrator.md");
    const tampered = readFileSync(victim, "utf8").replace(/^# Role: .+$/m, "# (stripped)");
    writeFileSync(victim, tampered);

    // Plant a sentinel the generator must NOT overwrite on the fail-closed path.
    const sentinel = "SENTINEL — must not be overwritten on a fail-closed run.\n";
    const outPath = join(m, "docs", "catalog", "README.md");
    writeFileSync(outPath, sentinel);

    const r = spawnSync("node", [join(m, "scripts", "generate-catalog.js")], {
      encoding: "utf8",
    });
    expect(r.status).toBe(1);
    // No partial write: the sentinel survives unchanged.
    expect(existsSync(outPath)).toBe(true);
    expect(readFileSync(outPath, "utf8")).toBe(sentinel);
  });

  // (5) no fabrication: workflows 12 (Release) and 13 (Incident) carry no `cadence` frontmatter, so
  // their cadence cell must read `UNKNOWN - verify` — never a fabricated `cadence: both` or bare
  // `both`. Also assert no `..` (double-period) anywhere (the incident-responder single-sentence
  // summary edge — appending a period would produce `..`).
  it("no fabrication: workflows 12/13 cadence reads UNKNOWN - verify, no fabricated cadence, no double-period", () => {
    const before = readFileSync(OUT);
    try {
      const r = spawnSync("node", [GEN_JS], { encoding: "utf8" });
      expect(r.status).toBe(0);
      const text = readFileSync(OUT, "utf8");

      // The two enterprise workflows with no cadence must surface UNKNOWN - verify.
      expect(text).toContain("UNKNOWN - verify");
      // No fabricated cadence value for the absent field.
      expect(text).not.toContain("cadence: both");
      // No FABRICATED double-period after a sentence (Pitfall 1 — incident-responder single-sentence
      // summary, where naively re-appending a period would yield `word..`). Scoped to that artifact
      // — a word char followed by `..` then whitespace/pipe/end-of-line — so it no longer false-fails
      // on the legitimate `../../` in the now-relative source links (or on `...` ellipses). (IN-03,
      // mandatory collateral of WR-02's relative-link form.)
      expect(text).not.toMatch(/\w\.\.(\s|\||$)/m);
    } finally {
      writeFileSync(OUT, before);
    }
  });
});
