// generate-skill-twins.ts — grugops standalone skill-twin generator (KIT-03 / SPAWN-04, Phase 27,
// plan 27-64, D-64 Part B).
//
// Reads the plugin-form skill corpus (skills/<d>/SKILL.md) and emits the standalone twin the
// un-namespaced `/grugops-<d>` command form needs (.claude/skills/grugops-<d>/SKILL.md), plus the
// namespace root (.claude/skills/grugops/SKILL.md).
//
// WHY THIS GENERATOR EXISTS — THE ASYMMETRY D-64 NAMES, AND IT IS THE WHOLE ARGUMENT.
//
//   • The seventeen agent adapters under .claude/agents are GENERATED by
//     scripts/generate-role-adapters.js and BYTE-GATED by scripts/adapters-freshness.js. They have
//     never been bypassed once.
//   • The fourteen SKILL.md files (seven plugin-form sources + seven standalone twins) were
//     HAND-AUTHORED, and before this plan no freshness gate in this tree named `SKILL` at all.
//   • Every bypass reproduced in every one of eleven review rounds landed in a SKILL.md.
//
// The strong mechanism already existed here, was proven, and had simply never been extended to the
// failing surface. This file and scripts/skill-twins-freshness.ts extend it. Nothing here is a new
// idea; every property below is copied deliberately from the adapter pair.
//
// THE TWINS ARE EXACTLY DERIVABLE, AND THAT WAS MEASURED RATHER THAN ASSUMED (on fb59ca6, and
// re-measured by this plan's own execution):
//
//   • The six non-root pairs differ by EXACTLY ONE LINE — `name: <d>` becomes `name: grugops-<d>` —
//     an eight-byte delta on each of gate, map, plan, release, ticket, uat. `/usr/bin/diff` reports
//     one changed line and nothing else.
//   • The root pair differs by a PURE INSERTION of eleven lines (+448 bytes) and NO changed line:
//     the root twin's `name` is `grugops` on both sides. Those eleven lines are the RESOLVER
//     constant (ten entries) plus one blank line.
//
// So generation is a name rewrite plus ONE known addendum. It is not a re-authoring, and this file
// deliberately contains no third rule.
//
// THE DERIVABILITY PREMISE IS ASSERTED, NOT ASSUMED — AND IT IS THE LOUD PATH. On every run each
// rendered twin is compared against the committed file at its path BEFORE anything is written. A
// committed twin that differs HALTS the run, printing the path, both byte lengths and a bounded
// line-level difference report — it is never silently overwritten. A generator that quietly rewrites
// its target proves nothing about derivability, and producing a convincing result without having
// measured anything is this phase's entire failure mode. `--overwrite-committed-twins` adopts a
// legitimate source change deliberately; the flag's NAME says what it does.
//
//   node scripts/generate-skill-twins.js                            # verify-only; exit 1 on drift
//   node scripts/generate-skill-twins.js --overwrite-committed-twins # adopt a source change
//
// Read/write-only by construction (path-traversal mitigation, ASVS V12, T-27-149): OUT_DIR is a
// FIXED literal joined to the repository root (this script's parent). It is never derived from argv,
// env or file content, and this script accepts NO output flag — scripts/skill-twins-freshness.ts
// mirrors the whole world into a temp tree rather than overriding a path, exactly as
// adapters-freshness.ts does, so a flag would break both the security posture and the gate.
//
// THE SET COMES FROM THE ONE KIT AUTHORITY, NEVER A PRIVATE readdir. Both sides are
// scripts/kit-model.ts's business: listPluginSkillAdapters() answers "what is a plugin-form skill
// entry point" and listSkillAdapters() answers it for the standalone tree. A second derivation of
// either rule inside a generator is the set-literal drift class this phase exists to close.
//
// THERE IS NO SECOND FRONTMATTER GRAMMAR IN THIS FILE. The VERDICT-bearing facts — how many `name`
// values a document declares and what they are — come from scripts/frontmatter.ts, the one
// authority. The rewrite below is a MECHANICAL SPLICE on a full-line exact-string match that those
// facts have already licensed, and it fails closed when it cannot find exactly one line to edit.
// This is the same arrangement `rewriteNameLine` in scripts/check-foundation-guards.ts already uses,
// for the same stated reason.
//
// Fail closed: an unreadable source, a `name` count other than one, a `name` value that disagrees
// with its own directory, a source path the naming rule cannot express, a non-ASCII path, a twin
// name collision, a missing or duplicated invariant line in the root source — every one prints a
// finding naming the file and exits 1 WITHOUT writing anything. The whole file set is rendered in
// memory first, so a partial or garbled twin directory never ships.
//
// The verdict states WHAT WAS DONE, never a bare success: twins rendered, written, already
// identical, and the output directory. A run that rendered ZERO twins is refused as the anomaly it
// is rather than reported as a clean pass over nothing.
//
// Node stdlib ONLY — node:fs + node:path, plus the in-repo kit-model and frontmatter modules. Zero
// npm dependencies.
//
// Findings are written in CLEAR PROFESSIONAL VOICE (CLAUDE.md hard rule — this is a build-safety
// surface, never caveman voice).

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { listPluginSkillAdapters, INVARIANT, RESOLVER } from "./kit-model.js";
import { parseFrontmatter } from "./frontmatter.js";

// ── Fixed literal paths (never argv/env/content-derived — ASVS V12) ───────────────────────────
const ROOT = join(import.meta.dirname, "..");
const SRC_SUBPATH = "skills";
const OUT_SUBPATH = ".claude/skills";
const OUT_DIR = join(ROOT, OUT_SUBPATH);

// The standalone tree's namespace. `.claude/skills` holds `grugops` itself and `grugops-<n>` for
// each command skill; the plugin tree drops the namespace because the platform supplies it. The ONE
// source directory whose own name IS the namespace is the kit root, and it is the only member that
// takes the resolver insertion.
const STANDALONE_NAMESPACE = "grugops";

// The flag is named for its effect. A flag called `--force` or `-f` would let a reader approve the
// overwrite of a committed artifact without ever reading what it overwrites.
const OVERWRITE_FLAG = "--overwrite-committed-twins";
const REGEN_CMD = `npm run generate:skill-twins -- ${OVERWRITE_FLAG}`;

// ── Fail-closed helper (a structural miss is a finding, never an unhandled throw) ──────────────
// The VARIABLE carries the `=> never` annotation for the same reason generate-role-adapters.ts does:
// TypeScript only narrows control flow through a never-returning call when the callee is a function
// declaration or a const with an explicit type annotation.
const fail: (m: string) => never = (m: string): never => {
  console.error(`  ERROR    ${m}`);
  process.exit(1);
};

// ── Argument handling: exactly one recognised flag, and every other argument is refused ────────
// An unrecognised argument is a finding rather than a silent no-op. A typo of the overwrite flag
// that was quietly ignored would leave the author believing a source change had been adopted.
const argv = process.argv.slice(2);
let overwrite = false;
for (const a of argv) {
  if (a === OVERWRITE_FLAG) {
    overwrite = true;
    continue;
  }
  fail(
    `unrecognised argument "${a}" — this generator accepts only ${OVERWRITE_FLAG}, and deliberately accepts NO output path (the output directory is a fixed literal, ASVS V12)`,
  );
}

// ── Read the plugin-form skill corpus through the SHARED authority (never a private readdir) ───
let srcRels: string[];
try {
  srcRels = listPluginSkillAdapters(ROOT);
} catch (e) {
  fail(`${(e as Error).message}`);
}
srcRels = srcRels!.slice().sort(); // explicit sort before emit (kit-model already sorts)

interface Twin {
  srcRel: string; // plugin-form relative path, e.g. map/SKILL.md
  dir: string; // map
  outRel: string; // grugops-map/SKILL.md
  isRoot: boolean;
  body: string;
}

const twins: Twin[] = [];

// Twin path FOLDED TO LOWER CASE -> the source that claimed it. The fold is the same point the
// adapter generator makes: two sources whose twin paths differ only by case are distinct files on a
// case-sensitive filesystem and the SAME file on a case-insensitive one (APFS, NTFS), where the
// second write silently destroys the first and the twin directory comes up one short with no error
// anywhere. grugops ships to Windows.
const seenOut = new Map<string, string>();

for (const srcRel of srcRels) {
  // Encoding gate: twin paths are compared by exact string equality by the freshness gate's set half
  // and as BYTES by its byte half. A non-ASCII path introduces normalisation ambiguity into both, so
  // it is refused here rather than left latent.
  // eslint-disable-next-line no-control-regex
  if (/[^\x00-\x7F]/.test(srcRel)) {
    fail(
      `${SRC_SUBPATH}/${srcRel}: non-ASCII byte in a skill path — twin paths are compared by exact string equality and written as bytes; rename the directory to ASCII`,
    );
  }

  // SHAPE: the naming rule is defined for `<dir>/SKILL.md` and for nothing else. The kit authority
  // walks at ANY depth on purpose, so a nested plugin skill is a real member of the corpus — and a
  // member whose twin path this rule cannot express is a FINDING, never a skipped file. Skipping it
  // would leave a live skill outside the byte gate, which is the exact silence this plan closes.
  const parts = srcRel.split("/");
  if (parts.length !== 2 || parts[1] !== "SKILL.md") {
    fail(
      `${SRC_SUBPATH}/${srcRel}: the twin naming rule is defined only for <dir>/SKILL.md, and this path is ${parts.length} segment(s) deep — a pair the rule cannot express is refused rather than skipped, because a skipped skill is a live file outside the byte gate`,
    );
  }
  const dir = parts[0];
  const isRoot = dir === STANDALONE_NAMESPACE;
  const twinDir = isRoot ? dir : `${STANDALONE_NAMESPACE}-${dir}`;
  const outRel = `${twinDir}/SKILL.md`;

  const folded = outRel.toLowerCase();
  const claimed = seenOut.get(folded);
  if (claimed !== undefined) {
    fail(
      `${SRC_SUBPATH}/${srcRel}: its twin path "${outRel}" collides with the one produced by ${SRC_SUBPATH}/${claimed} — two skills cannot share one twin file (paths are compared case-insensitively: on a case-insensitive filesystem the second twin silently overwrites the first)`,
    );
  }
  seenOut.set(folded, srcRel);

  const srcPath = join(ROOT, SRC_SUBPATH, srcRel);
  let text: string;
  try {
    text = readFileSync(srcPath, "utf8");
  } catch {
    fail(`cannot read the plugin-form skill: ${srcPath}`);
  }

  // ── The declared name, read through the ONE frontmatter authority ───────────────────────────
  // A PARSE FAILURE IS A PARSE ARTIFACT, NEVER A VERDICT (frontmatter.ts header): an unreadable
  // source is a different fact from a source declaring the wrong name, and the two never print the
  // same sentence.
  const parsed = parseFrontmatter(text!);
  if (!parsed.ok) {
    fail(`${SRC_SUBPATH}/${srcRel}: frontmatter is unreadable — ${parsed.reason}`);
  }
  const names = parsed.value.get("name") ?? [];
  if (names.length !== 1) {
    // The authority retains EVERY occurrence of a key rather than last-wins, because silently
    // discarding a declaration is the bypass shape this project refuses. The count is named so the
    // author sees how many were found instead of being told to look for "a duplicate" that may be
    // three.
    fail(
      `${SRC_SUBPATH}/${srcRel}: declares ${names.length} \`name\` value(s), expected exactly 1 — the twin transform rewrites exactly one name line, so anything other than one answer is refused rather than guessed at`,
    );
  }
  if (names[0] !== dir) {
    // THE VALUE ASSERTION THAT MAKES THE REWRITE MEAN SOMETHING. The plugin form's name is the
    // command the platform namespaces, so a wrong value is a wrong command — and a transform that
    // rewrote it to the twin's expected name regardless would launder exactly that error into a
    // passing byte gate.
    fail(
      `${SRC_SUBPATH}/${srcRel}: declares \`name: ${names[0]}\`, expected \`name: ${dir}\` — the plugin form's name is the command the platform namespaces, so a wrong value is a wrong command and rewriting it away would hide it`,
    );
  }

  const lines = text!.split("\n");

  if (!isRoot) {
    // ── RULE ONE: rewrite the frontmatter `name` value, and nothing else ──────────────────────
    // A MECHANICAL SPLICE licensed by the authority's facts above, deliberately NOT a second
    // frontmatter grammar and deliberately NOT a text substitution over the document. The match is
    // FULL-LINE EXACT-STRING equality, and the count is required to be exactly one: a body
    // occurrence of the directory name cannot be rewritten (it is not a whole line of this shape),
    // and a document that spells the line twice HALTS rather than having one of them picked.
    const target = `name: ${dir}`;
    const at: number[] = [];
    for (let i = 0; i < lines.length; i++) if (lines[i] === target) at.push(i);
    if (at.length !== 1) {
      fail(
        `${SRC_SUBPATH}/${srcRel}: the line \`${target}\` occurs ${at.length} time(s), expected exactly 1 — the parser reports one \`name\` value that the text does not express as exactly one plain line, so the rewrite is refused rather than performed on a document it cannot locate`,
      );
    }
    lines[at[0]] = `name: ${STANDALONE_NAMESPACE}-${dir}`;
  } else {
    // ── RULE TWO: insert the resolver block, and nothing else ─────────────────────────────────
    // The root twin's `name` is `grugops` on BOTH sides, so it takes no rewrite. What it takes is
    // the eleven-line addendum: the RESOLVER constant plus one blank line, immediately after the
    // kit-vs-state invariant line and the blank line that follows it. That is the same
    // INVARIANT / "" / RESOLVER / "" ordering every agent adapter body carries, which is why both
    // constants live in the kit authority rather than being retyped here.
    //
    // The landmark is located by FULL-LINE EXACT-STRING equality against the imported constant, and
    // BOTH its cardinality and the blank line after it are asserted. An insertion performed at a
    // guessed position is how a generator produces a plausible artifact nobody measured.
    const at: number[] = [];
    for (let i = 0; i < lines.length; i++) if (lines[i] === INVARIANT) at.push(i);
    if (at.length !== 1) {
      fail(
        `${SRC_SUBPATH}/${srcRel}: the kit-vs-state invariant line occurs ${at.length} time(s), expected exactly 1 — it is the landmark the resolver block is inserted after, and an insertion at a guessed position is refused`,
      );
    }
    if (lines[at[0] + 1] !== "") {
      fail(
        `${SRC_SUBPATH}/${srcRel}: the kit-vs-state invariant line is not followed by a blank line — the resolver block is inserted after that blank line, so the landmark's shape is asserted rather than assumed`,
      );
    }
    lines.splice(at[0] + 2, 0, ...RESOLVER, "");
  }

  twins.push({ srcRel, dir, outRel, isRoot, body: lines.join("\n") });
}

// ── Refuse an empty render (vacuity): a run that produced nothing is the anomaly ───────────────
// kit-model's own refuseEmpty normally fires first on an unreadable or empty source tree. This arm
// covers the distinct condition of a corpus that listed members none of which produced a twin, and
// it exists so a zero-twin run can never read as a clean pass over nothing.
if (twins.length === 0) {
  fail(
    `no skill twins were rendered from ${join(ROOT, SRC_SUBPATH)} — refusing to report an empty generation as success`,
  );
}

// ── Assert the derivability premise BEFORE writing anything ────────────────────────────────────
// Each rendered twin is compared against the committed file at its path. The three outcomes are
// distinct facts and are counted separately, so the verdict line states what was DONE.
const MAX_REPORTED_DIFF_LINES = 10;
const MAX_REPORTED_LINE_CHARS = 200;

// A BOUNDED line-level difference report. Deliberately not a unified diff — this is a report of the
// first differing lines with their 1-based numbers, truncated on both axes, so a 400 KB divergence
// cannot flood a build log while still telling the reader exactly where to look.
function boundedDifference(committed: string, rendered: string): string {
  const a = committed.split("\n");
  const b = rendered.split("\n");
  const clip = (s: string): string =>
    s.length > MAX_REPORTED_LINE_CHARS
      ? `${s.slice(0, MAX_REPORTED_LINE_CHARS)}… (${s.length}B, truncated)`
      : s;
  const out: string[] = [];
  let shown = 0;
  const n = Math.max(a.length, b.length);
  for (let i = 0; i < n && shown < MAX_REPORTED_DIFF_LINES; i++) {
    const left = i < a.length ? a[i] : null;
    const right = i < b.length ? b[i] : null;
    if (left === right) continue;
    out.push(`    line ${i + 1}:`);
    out.push(`      committed: ${left === null ? "(absent)" : clip(left)}`);
    out.push(`      generated: ${right === null ? "(absent)" : clip(right)}`);
    shown += 1;
  }
  if (shown === MAX_REPORTED_DIFF_LINES) {
    out.push(`    … report truncated at ${MAX_REPORTED_DIFF_LINES} differing line(s)`);
  }
  return out.join("\n");
}

let identical = 0;
const toWrite: { path: string; body: string; outRel: string }[] = [];
let divergence = "";

for (const t of twins) {
  const outPath = join(OUT_DIR, t.outRel);
  let committed: string | null;
  try {
    committed = readFileSync(outPath, "utf8");
  } catch {
    // An absent twin is not a divergence — it is a twin this generator has not written yet, and
    // writing it is the whole job. An UNREADABLE-but-present twin is indistinguishable from an
    // absent one here by design: either way the generator's own output is authoritative and the
    // freshness gate is the surface that judges the committed tree.
    committed = null;
  }
  if (committed === null) {
    toWrite.push({ path: outPath, body: t.body, outRel: t.outRel });
    continue;
  }
  if (committed === t.body) {
    identical += 1;
    continue;
  }
  if (overwrite) {
    toWrite.push({ path: outPath, body: t.body, outRel: t.outRel });
    continue;
  }
  divergence +=
    `\n  ${OUT_SUBPATH}/${t.outRel} (from ${SRC_SUBPATH}/${t.srcRel}) — committed ${Buffer.byteLength(committed, "utf8")}B, generated ${Buffer.byteLength(t.body, "utf8")}B\n` +
    boundedDifference(committed, t.body) +
    "\n";
}

if (divergence !== "") {
  fail(
    `the committed skill twin(s) below are NOT this generator's output, and nothing was written:\n${divergence}\n` +
      `  A generator that silently rewrites its target proves nothing about derivability, so this run HALTED instead.\n` +
      `  If the plugin-form source changed legitimately, adopt it deliberately: \`${REGEN_CMD}\`, then commit the result.\n` +
      `  If it did not, the committed twin was hand-edited — restore it from the source rather than teaching this generator a new rule.`,
  );
}

// ── Write (T-27-32 posture: a structural miss never leaves a partial artifact) ─────────────────
// Every refusal above happened before this loop, so the directory is only ever touched by a run that
// has already rendered and verified the complete set.
for (const w of toWrite) {
  try {
    mkdirSync(dirname(w.path), { recursive: true });
  } catch {
    fail(`cannot create the twin directory: ${dirname(w.path)}`);
  }
  writeFileSync(w.path, w.body, "utf8");
}

console.log(
  `generate-skill-twins: rendered ${twins.length} twin(s) from ${SRC_SUBPATH}, ${toWrite.length} written, ${identical} already identical, into ${OUT_DIR}`,
);
process.exit(0);
