// generate-asvs-checklist.test.ts — SEC-02 / TOOL-01 oracle for the ASVS checklist generator
// (Vitest harness for scripts/generate-asvs-checklist.js).
//
// Drives the COMMITTED compiled artifact scripts/generate-asvs-checklist.js (never the .ts) and
// asserts the contract:
//   (1) it writes the checklist and exits 0 over the real source;
//   (2) BYTE-REPRODUCIBILITY: regenerating twice produces a byte-identical file (the freshness
//       gate AND the security-checklist provenance both depend on this);
//   (3) FAIL-CLOSED row-count: a truncated/tampered source (row count != 345) → exit 1, no
//       partial write — proven hermetically so the real source/checklist are never touched.
//
// The generator's SRC and OUT are FIXED literal paths joined to its own repo root (path-traversal
// mitigation — never argv/env/content-derived). So the fail-closed case copies the generator .js
// plus a tampered source + a sentinel output into a temp mirror laid out as <tmp>/scripts/... and
// <tmp>/agent-factory/checklists/..., then runs the mirrored .js there. The real tree is read-only
// in tests (1) and (2) and untouched in (3).
//
// Spawns the COMMITTED compiled .js, mirroring the spawnSync child-CLI test idiom.

import { describe, it, expect, afterAll } from "vitest";
import { spawnSync, type SpawnSyncReturns } from "node:child_process";
import {
  mkdtempSync,
  mkdirSync,
  cpSync,
  rmSync,
  readFileSync,
  writeFileSync,
  existsSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

const ROOT = join(import.meta.dirname, "..");
const GEN_JS = join(ROOT, "scripts", "generate-asvs-checklist.js");
const SRC = join(ROOT, "scripts", "asvs", "asvs-5.0.0.flat.json");
const OUT = join(ROOT, "agent-factory", "checklists", "security-nfr-checklist.md");

const tmpDirs: string[] = [];
afterAll(() => {
  for (const d of tmpDirs) rmSync(d, { recursive: true, force: true });
});

function out(r: SpawnSyncReturns<string>): string {
  return `${r.stdout ?? ""}${r.stderr ?? ""}`;
}

describe("generate-asvs-checklist.js (SEC-02 / TOOL-01)", () => {
  // (1) writes the checklist + exits 0 over the real source. The regenerated bytes are identical
  // to what is already committed (parity), so the real tree is left clean.
  it("writes the checklist and exits 0", () => {
    const before = readFileSync(OUT);
    const r = spawnSync("node", [GEN_JS], { encoding: "utf8" });
    try {
      expect(r.status).toBe(0);
      expect(out(r)).toContain("345 requirements");
      const after = readFileSync(OUT);
      expect(after.length).toBeGreaterThan(0);
      // The committed checklist IS the generator's deterministic output, so a regen is a no-op.
      expect(after.equals(before)).toBe(true);
    } finally {
      // Defensive: restore the original bytes even if a future source drift made the regen differ.
      writeFileSync(OUT, before);
    }
  });

  // (2) byte-reproducibility: two successive regenerations produce byte-identical output.
  it("byte-reproducible: regenerating twice yields identical bytes", () => {
    const before = readFileSync(OUT);
    try {
      const r1 = spawnSync("node", [GEN_JS], { encoding: "utf8" });
      expect(r1.status).toBe(0);
      const first = readFileSync(OUT);
      const r2 = spawnSync("node", [GEN_JS], { encoding: "utf8" });
      expect(r2.status).toBe(0);
      const second = readFileSync(OUT);
      expect(second.equals(first)).toBe(true);
      // …and identical to the committed bytes (no drift from the parity baseline).
      expect(second.equals(before)).toBe(true);
    } finally {
      writeFileSync(OUT, before);
    }
  });

  // (3) fail-closed row-count: a tampered source (< 345 rows) → exit 1, NO partial write. Built
  // hermetically: mirror the generator .js + a truncated source into <tmp>/scripts/..., point a
  // sentinel OUT at <tmp>/agent-factory/checklists/..., run the mirrored .js, assert exit 1 AND
  // the sentinel output is unchanged (refused to write a partial).
  it("fail-closed: a truncated source (row count != 345) → exit 1, no partial write", () => {
    const m = mkdtempSync(join(tmpdir(), "grugops-asvs-"));
    tmpDirs.push(m);
    // Lay out the generator's expected structure: <m>/scripts/generate-asvs-checklist.js,
    // <m>/scripts/asvs/asvs-5.0.0.flat.json, <m>/agent-factory/checklists/security-nfr-checklist.md.
    mkdirSync(join(m, "scripts", "asvs"), { recursive: true });
    mkdirSync(join(m, "agent-factory", "checklists"), { recursive: true });
    cpSync(GEN_JS, join(m, "scripts", "generate-asvs-checklist.js"));
    // Truncate the source to a single requirement (row count 1 != 345).
    const full = JSON.parse(readFileSync(SRC, "utf8"));
    const tampered = { ...full, requirements: full.requirements.slice(0, 1) };
    writeFileSync(
      join(m, "scripts", "asvs", "asvs-5.0.0.flat.json"),
      JSON.stringify(tampered),
    );
    // Plant a sentinel output the generator must NOT overwrite on the fail-closed path.
    const sentinel = "SENTINEL — must not be overwritten on a fail-closed run.\n";
    const outPath = join(m, "agent-factory", "checklists", "security-nfr-checklist.md");
    writeFileSync(outPath, sentinel);

    const r = spawnSync(
      "node",
      [join(m, "scripts", "generate-asvs-checklist.js")],
      { encoding: "utf8" },
    );
    expect(r.status).toBe(1);
    expect(out(r)).toMatch(/refusing to write a partial checklist/i);
    // No partial write: the sentinel survives unchanged.
    expect(existsSync(outPath)).toBe(true);
    expect(readFileSync(outPath, "utf8")).toBe(sentinel);
  });
});
